### ISSUE TITLE
Clang Support

### ISSUE THREAD

**Issue by Ozomahtli** [zhihaoy/nontype_functional#5]
Hello! Is clang support planned ?

Latest clang fails to parse with `c++2b`
https://godbolt.org/z/8bnro63qf

**Comment by zhihaoy** [comment]
It parses with the absolutely latest Clang: https://godbolt.org/z/jE5Yj1hb7
After Clang 16 is released, it will become meaningful to `#ifdef` some tests if necessary.
The roadmap is to get inclusion in vcpkg, so Clang support is needed.

**Comment by spnda** [comment]
I'm trying to use this library with Clang 18, and the last link you sent actually doesn't compile anymore with the latest Clang.

Are there any alternatives? Are you still maintaining this? Clang 18's libc++ still has no `move_only_function` implementation...

**Comment by zhihaoy** [comment]
The link used godblot's http-`#include`, so it's now a mixture of old and new code. But indeed, the latest Clang broke something, probably due to the recent P3310/P0522 implementation effort. I've inquired the author.

**Comment by gotnone** [comment]
Any movement on this?  I use clangd as my LSP and I get a message in my editor when I `#include "std23/function_ref.h"`:

`Diagnostics:
 In included file: template template argument has different template parameters than its corresponding template template parameter [template_arg_template_params_mismatch]`

**Comment by zhihaoy** [comment]
Given the direction of [P3310R4](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3310r4.html), we may have to turn that `template<class>` into `template<class...>` https://github.com/zhihaoy/nontype_functional/blob/83ba1aebdb22f9aa806166467da76bf04e0b07c8/include/std23/__functional_base.h#L50
If you can verify, patch is welcome.
