### ISSUE TITLE
Clang: Cannot overload a member function with ref-qualifier '&' with a member function without a ref-qualifier

### ISSUE THREAD

**Issue by louwers** [zhihaoy/nontype_functional#8]
We are having some compilation problems on C++20 with clang.

Could you advice?

https://godbolt.org/z/e5EGqdsv6

**Comment by louwers** [comment]
Ah I now see that clang is not one of the supported toolchains.

**Comment by zhihaoy** [comment]
Please give the https://github.com/zhihaoy/nontype_functional/tree/compat branch a try.

**Comment by zhihaoy** [comment]
AppleClang >= 16.0.0 (Clang 17) is now a supported toolchain on `main` in C++20 mode. But strangely, you'll again see those errors in Clang 18 and above if you're passing `-std=c++20` rather than `-std=c++23`. It doesn't bother me enough, though.
